# Dependencies
gems:             [jekyll-paginate]
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Casey Knox
tagline:          'Portfolio'
description:      'An expert in real world sensor integration and computer vision'
# baseurl:          "\/"
url:              'http://caseyknox.github.io'

author:
  name:           'Casey Knox'
  # url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/caseyknox
